run:
  timeout: 5m
linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gofmt
    - goimports
    - gosimple
    - misspell
    - errcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
