version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: ["8081:8080"]
volumes:
  dbdata:
